pipeline {
  agent any
  environment {
    GOOGLE_APPLICATION_CREDENTIALS = credentials('gcp')
  }
  tools {
    terraform "terraform"
  }
  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'main', credentialsId: 'github', url: 'https://github.com/jherreralizalde/gcp_demo_t2'
      }
    }
    stage('Terraform Init') {
      steps { 
        sh 'terraform -chdir=enviroment/dev init'
      }
    }
      stage('Terraform Plan') {
        steps { 
          sh 'terraform -chdir=enviroment/dev plan -out myplan'
          sh 'ls'
        }
      }
      stage('Terraform apply') {
        steps {
          sh 'terraform -chdir=enviroment/dev apply -input=false myplan'
          sh 'ls'
        }
      }
     stage('Terraform destroy') {
         input {
                message "Do you want to apply the change?"
            }
        steps {
          
          sh 'terraform -chdir=enviroment/dev destroy -input=false myplan'
          sh 'ls'
        }
      } 
    }
  }